// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0ffoQQG7YcJBlDXGE8byTNR48ZtpF9TM',
    appId: '1:1090433339137:web:13d24ba54a460a9a1d5500',
    messagingSenderId: '1090433339137',
    projectId: 'flutter-ticketing',
    authDomain: 'flutter-ticketing.firebaseapp.com',
    storageBucket: 'flutter-ticketing.firebasestorage.app',
    measurementId: 'G-TB6GL1W24B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJOhP-x3HhaJh2pbnLgecRIA_ohnMTiZ0',
    appId: '1:1090433339137:android:0da883f4793283851d5500',
    messagingSenderId: '1090433339137',
    projectId: 'flutter-ticketing',
    storageBucket: 'flutter-ticketing.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgMqtDMAePKlEKmyRgr7SVyesGr0KswpA',
    appId: '1:1090433339137:ios:b2ccf1df4737469c1d5500',
    messagingSenderId: '1090433339137',
    projectId: 'flutter-ticketing',
    storageBucket: 'flutter-ticketing.firebasestorage.app',
    iosBundleId: 'com.example.skl1EventTicketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgMqtDMAePKlEKmyRgr7SVyesGr0KswpA',
    appId: '1:1090433339137:ios:b2ccf1df4737469c1d5500',
    messagingSenderId: '1090433339137',
    projectId: 'flutter-ticketing',
    storageBucket: 'flutter-ticketing.firebasestorage.app',
    iosBundleId: 'com.example.skl1EventTicketing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0ffoQQG7YcJBlDXGE8byTNR48ZtpF9TM',
    appId: '1:1090433339137:web:1d65faf7c85b5d091d5500',
    messagingSenderId: '1090433339137',
    projectId: 'flutter-ticketing',
    authDomain: 'flutter-ticketing.firebaseapp.com',
    storageBucket: 'flutter-ticketing.firebasestorage.app',
    measurementId: 'G-J493FGGS9K',
  );
}
